### ISSUE TITLE
Fix issue with output relation

### ISSUE THREAD

**Issue by agouy** [tercen/debarcoding_cytof_operator#2]
Barcodes seem to be randomly distributed across observations.

**Comment by tsmonteiro** [comment]
This issue should now be fixed in version 0.0.3. The problem was that .ci was mapped to .i multiple times (once per row) instead of uniquely per column. Here is how the output looks like now:

![image](https://user-images.githubusercontent.com/10157888/200345930-4c2ed4e3-40e3-4b19-8d5b-f1d4eeae39f9.png)

**Comment by agouy** [comment]
Beautiful, thanks @tsmonteiro
