### ISSUE TITLE
Missing channels after debarcoding

### ISSUE THREAD

**Issue by makostadima** [tercen/debarcoding_cytof_operator#5]
So I am working on the small-ish CyTOF dataset from Christoph at EPFL.

I have gathered all channels (including Center, Event_length, Residual and Width) and then I am filtering some channels that are present in the dataset, but aren't used. (relevant [data step](https://tercen.com/FCF_Tercen/w/d67039b638785c110af72e9fb46e5e57/ds/02799d12-8a9b-45da-a559-ca884280227c))

And then I go on to perform debarcoding. All good up until this point.

If I add a data step after debarcoding, why I don't have anymore access to the extra information (Center, Event_length, Residual and Width) when adding the barcodes on the columns? (relevant [data step](https://tercen.com/FCF_Tercen/w/d67039b638785c110af72e9fb46e5e57/ds/21d03e60-a251-4af2-ad82-3bc2e123f628)).

**Comment by tsmonteiro** [comment]
Hi @makostadima ,

I am looking into this issue, but just so that I have a clear understanding of what is going on: you have a gathered variable (let's say Center) which is in Data Step 'Filtering Out ...' that is the input projection for Data Step 'Debarcoding'. Then you create a new Data Step and the row 'Center' is not an output of Data Step 'Debarcoding', is that right? Or you want to access the one directly from 'Filtering Out'... ?

I ask this because Center and the other variables are removed by CATALYST during the assignPrelim step (so these would not be included in the output) possibly due to not being present in the sample key auxiliary file.

What would be the expected behavior or output in this situation?

**Comment by tsmonteiro** [comment]
@makostadima I have changed how the output projections are handled in version 0.1.0 (see below). Could you please check that this fixes the issue?

One thing to note is that the operator now uses the multi-data step. There are no unit tests implemented for it yet (tercen-wise), so I believe you will not be able install in tercen.com, only stage.

![image](https://user-images.githubusercontent.com/10157888/235508431-bcfea8eb-dc93-4561-ab31-12bb4cebbb85.png)

**Comment by makostadima** [comment]
@tsmonteiro @agouy I am looking into this right now and I noticed the following behaviour:

1. The factor that is output by the debarcoding operator for the description of the "missing channels" is empty.

![Asinh Transformation](https://github.com/tercen/debarcoding_cytof_operator/assets/1746464/8aafc924-e701-4e1b-a645-3a86815911b1)

2. They don't have a rowId attached to them anymore and are under NaN:

![image](https://github.com/tercen/debarcoding_cytof_operator/assets/1746464/22dcf64b-0d89-4f96-b108-92cb19b1a716)

Are these two things expected?

**Comment by makostadima** [comment]
@agouy 

relevant workflow on stage: https://stage.tercen.com/myrto.kostadima/w/eb5fe0e4ccbb270d9cbef9a13c74be1c

relevant debarcoding step: https://stage.tercen.com/myrto.kostadima/w/eb5fe0e4ccbb270d9cbef9a13c74be1c/ds/bef4a302-027e-41a9-85ea-af35193e7745

**Comment by agouy** [comment]
Fixed - issue likely related to duplicated factor name in output relations
