### ISSUE TITLE
Fix memory usage issue

### ISSUE THREAD

**Issue by agouy** [tercen/debarcoding_cytof_operator#6]
Might be related to the way relations are made and related to https://github.com/tercen/debarcoding_cytof_operator/issues/5.

The operator should output three relations:
* Scaled values with rows and columns (.ci, .ri)
* Barcodes and columns (.ci)
* Diagnostic plots (no relation)

They might need to be part of independent "join operators" and the operator would output a lsit of join operators and not a single join operator.

Naming multiple factors ".i" might be an issue as well.

**Comment by tsmonteiro** [comment]
I am not sure we will be able to solve this by adjusting the code. I probed this issue using the pryr library to get memory usage at different points and made a few observations:

1) A dataset of 120000 rows (the one they used in the tutorial) takes ~710mb to run locally from within RStudio.

2) The same dataset requires ~1.3 Gb to run in my local tercen instance. I am currently assuming this difference comes from 2 separate places. One is related to memory that is allocated and deallocated in between mem_used() calls (see point 5). The other source of usage is tercen itself, though I am not sure how much can be attributed to that.

3) All the plots only add about 10mb to the total plus some ~100mb during the processing (the 100mb I have estimated from my local tercen instance)

4) I have called mem_used() across many different point in the code. The largest impact comes from loading the libraries:
              [1] "Start: 44 mb"
              [1] "Libraries loaded: 638 mb"
Looking further into it, the main culprits are openCyto and CATALYST. CATALYST seems to require ~500mb of memory, while openCyto requires a little less than 300mb, though there is an overlap of required libraries.

The full trace is below. Creating tercen context has the largest impact, but nothing remarkable. I have run this 3 times and the results were very consistent.

> [1] "Start: 44 mb"
> [1] "Libraries loaded: 638 mb"
> [1] "Before calling op function: 669 mb"
> [1] "After loading sample key matrix: 676 mb"
> [1] "Before debarcoding: 683 mb"
> [1] "Before data matrix: 690 mb"
> [1] "After data matrix: 692 mb"
> [1] "Before flow frame: 692 mb"
> [1] "Before prep data: 692 mb"
> [1] "Before assign prelim: 695 mb"
> Debarcoding data...
>  o ordering
>  o classifying events
> Normalizing...
> Computing deltas...
> [1] "Before est cutoff: 697 mb"
> [1] "Before plot: 699 mb"
> [1] "After plot: 709 mb"
> [1] "task is null, create a task"


5) In addition to this, I have used library profvis to measure memory consumption per line. No particular line stood out, but the assignPrelim and estCutoff assigned about 200mb-300mb which were deallocated within the function. Given the memory used at that point, memory requirements at that point might reach ~1Gb. Something similar happens while plotting.

One additional note. If I got it right, Alexandre Maurel told me that there is currently no environment for testing. This means that the memory custom setting is not applied during the github action. Normally this is not an issue as the testing data sets are tiny, but since jsut loading the library takes more than 600mb, this seems to create the issue. There is a separate runner that is already in the CI and release workflow that should handle this, but it cannot be tested as unit tests are not implemented for multidata step.

**Comment by agouy** [comment]
Thanks for the extensive resource usage investigation. Then it seems there's nothing much we can do from the code perspective if we keep using CATALYST. The memory it requires for loading should not scale with data size, which is good.

Good to know about the absence of environment for testing. This is something that we'll need to be working on soon. Then the operator should work for the large dataset without having to hardcode the memory request within the operator, correct @tsmonteiro ?

**Comment by tsmonteiro** [comment]
I am positive about it. We just need to set the environment as we normally would. I will perform some tests today and then release a new version.

The one thing to note is that, since there are no unit tests for the multidata step, it cannot be installed in tercen.com. It can be tested in the stage server though

**Comment by tsmonteiro** [comment]
Since this is an issue of baseline memory required by CATALYST, I believe this issue is solved in version 0.1.0
